//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public Nullable<int> MerId { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BuyOn { get; set; }
        public Nullable<System.DateTime> ProduceOn { get; set; }
        public Nullable<int> KeepDay { get; set; }
        public Nullable<double> BuyPrice { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public Nullable<byte> State { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> TeBi { get; set; }
        public Nullable<double> Rmb { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public int IsDel { get; set; }
        public System.Guid Gid { get; set; }
        public System.Guid TypeId { get; set; }
        public int Inventory { get; set; }
        public string ShortCode { get; set; }
    }
}
