//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public string UserName { get; set; }
        public System.DateTime LogOnTime { get; set; }
        public Nullable<System.DateTime> LogOutTime { get; set; }
        public int MerId { get; set; }
    }
}
