//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberDc
    {
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public int IsDel { get; set; }
        public System.Guid Gid { get; set; }
        public System.Guid DcId { get; set; }
        public Nullable<System.DateTime> StarHour { get; set; }
        public Nullable<System.DateTime> EndHour { get; set; }
        public decimal Rmb { get; set; }
        public decimal TeRmb { get; set; }
        public int TeBi { get; set; }
    
        public virtual Discount Discount { get; set; }
    }
}
