//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchants
    {
        public int MerId { get; set; }
        public string Number { get; set; }
        public string MerchantsName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.Guid> MerNumber { get; set; }
        public string MerLogo { get; set; }
        public Nullable<int> First_Area_Id { get; set; }
        public Nullable<int> Second_Area_Id { get; set; }
        public Nullable<int> Third_Area_Id { get; set; }
        public Nullable<int> Fourth_Area_Id { get; set; }
        public int IsDel { get; set; }
        public System.Guid Gid { get; set; }
        public string MerNumberStr { get; set; }
    }
}
