//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class billiardEntities1 : DbContext
    {
        public billiardEntities1()
            : base("name=billiardEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BallTables> BallTables { get; set; }
        public DbSet<BallTableType> BallTableType { get; set; }
        public DbSet<Bento> Bento { get; set; }
        public DbSet<BillardMast> BillardMast { get; set; }
        public DbSet<BilliardsBaby> BilliardsBaby { get; set; }
        public DbSet<Buy> Buy { get; set; }
        public DbSet<Discount> Discount { get; set; }
        public DbSet<Goods> Goods { get; set; }
        public DbSet<LightControl> LightControl { get; set; }
        public DbSet<LoginLog> LoginLog { get; set; }
        public DbSet<Logs> Logs { get; set; }
        public DbSet<Machine> Machine { get; set; }
        public DbSet<MarginCustomer> MarginCustomer { get; set; }
        public DbSet<MemberDc> MemberDc { get; set; }
        public DbSet<MemberType> MemberType { get; set; }
        public DbSet<Merchants> Merchants { get; set; }
        public DbSet<Notifies> Notifies { get; set; }
        public DbSet<O2OPayInfo> O2OPayInfo { get; set; }
        public DbSet<OpenCardRecord> OpenCardRecord { get; set; }
        public DbSet<OptRecord> OptRecord { get; set; }
        public DbSet<OptRecordBak> OptRecordBak { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<ProductType> ProductType { get; set; }
        public DbSet<ProgramUpdateConfig> ProgramUpdateConfig { get; set; }
        public DbSet<RechargeRecord> RechargeRecord { get; set; }
        public DbSet<RechargeSetting> RechargeSetting { get; set; }
        public DbSet<RecordAccount> RecordAccount { get; set; }
        public DbSet<RecordAccountDetail> RecordAccountDetail { get; set; }
        public DbSet<Relay> Relay { get; set; }
        public DbSet<RepayRecord> RepayRecord { get; set; }
        public DbSet<Resource> Resource { get; set; }
        public DbSet<RoleAccess> RoleAccess { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<SparringRecord> SparringRecord { get; set; }
        public DbSet<SqlSrcipt> SqlSrcipt { get; set; }
        public DbSet<SwitchRecord> SwitchRecord { get; set; }
        public DbSet<SystemSettings> SystemSettings { get; set; }
        public DbSet<T_Command> T_Command { get; set; }
        public DbSet<T_CommandBak> T_CommandBak { get; set; }
        public DbSet<Transition> Transition { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<UserInRole> UserInRole { get; set; }
        public DbSet<WarehousingRecord> WarehousingRecord { get; set; }
        public DbSet<WatchBallTableRecord> WatchBallTableRecord { get; set; }
        public DbSet<WaveClock> WaveClock { get; set; }
    }
}
