//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenCardRecord
    {
        public System.Guid OcrId { get; set; }
        public Nullable<int> MerId { get; set; }
        public Nullable<long> TranNo { get; set; }
        public string PhoneNum { get; set; }
        public string CardNum { get; set; }
        public Nullable<int> DredgeStatus { get; set; }
        public Nullable<double> CardBalance { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string Name { get; set; }
        public string IdCard { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public bool IsDel { get; set; }
    }
}
