//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Buy = new HashSet<Buy>();
            this.SwitchRecord = new HashSet<SwitchRecord>();
        }
    
        public System.Guid OrId { get; set; }
        public Nullable<int> MerId { get; set; }
        public Nullable<int> GoTebi { get; set; }
        public Nullable<byte> CustomerType { get; set; }
        public string Customer { get; set; }
        public Nullable<int> DiscountCoe { get; set; }
        public Nullable<double> DrinkAmounts { get; set; }
        public string TableNumber { get; set; }
        public string TableName { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> FirstTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<double> RateAmounts { get; set; }
        public string Formula { get; set; }
        public Nullable<double> DiscountAmounts { get; set; }
        public Nullable<double> AccountsAmounts { get; set; }
        public Nullable<double> PaidAmounts { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public Nullable<double> Margin { get; set; }
        public Nullable<int> PaidTeBi { get; set; }
        public Nullable<int> TeBi { get; set; }
        public Nullable<int> PaidTeBall { get; set; }
        public Nullable<int> TeBall { get; set; }
        public Nullable<double> Change { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string MarginName { get; set; }
        public Nullable<double> MasterAmmount { get; set; }
        public Nullable<int> PayType { get; set; }
        public Nullable<long> TranNo { get; set; }
        public string PayNumber { get; set; }
        public Nullable<bool> PayStatus { get; set; }
        public Nullable<double> RecCardMoney { get; set; }
        public Nullable<long> TshUId { get; set; }
        public string MobileNum { get; set; }
        public System.Guid BtId { get; set; }
        public int CloseTableTerminal { get; set; }
        public int PayTerminal { get; set; }
        public decimal CardBalance { get; set; }
        public decimal BentoAmount { get; set; }
        public decimal StandTime { get; set; }
        public decimal StandAmount { get; set; }
        public Nullable<System.DateTime> ActualBillingTime { get; set; }
        public Nullable<System.Guid> MergeToOrder { get; set; }
        public string MergeMessage { get; set; }
        public int MergeRole { get; set; }
        public string NewOrId { get; set; }
        public string OldRateByHouer { get; set; }
        public Nullable<int> OnlinePayType { get; set; }
        public Nullable<System.Guid> MarginId { get; set; }
    
        public virtual ICollection<Buy> Buy { get; set; }
        public virtual ICollection<SwitchRecord> SwitchRecord { get; set; }
    }
}
