//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechargeRecord
    {
        public System.Guid RecId { get; set; }
        public Nullable<System.Guid> OcrId { get; set; }
        public Nullable<long> TranNo { get; set; }
        public Nullable<double> RechargeMoney { get; set; }
        public Nullable<double> DonateMoney { get; set; }
        public Nullable<int> DonateTeBi { get; set; }
        public Nullable<double> RecBalance { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
