//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transition
    {
        public System.Guid TrId { get; set; }
        public Nullable<int> MerId { get; set; }
        public Nullable<double> DrinkAmounts { get; set; }
        public Nullable<double> OperatAmounts { get; set; }
        public Nullable<double> RateAmounts { get; set; }
        public Nullable<double> OperatCash { get; set; }
        public string FromUser { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public string ToUser { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public Nullable<System.DateTime> OnTime { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<double> Balances { get; set; }
        public Nullable<double> PaidBalances { get; set; }
        public Nullable<int> TeBi { get; set; }
        public Nullable<int> PaidTeBi { get; set; }
        public Nullable<double> CheckAmount { get; set; }
        public Nullable<int> TeBall { get; set; }
        public Nullable<int> PaidTeBall { get; set; }
        public Nullable<int> OweTeBall { get; set; }
        public Nullable<double> TotalOperatAmounts { get; set; }
        public Nullable<double> PaidCash { get; set; }
        public Nullable<double> OweCash { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<double> MasterAmmount { get; set; }
        public Nullable<long> TranNo { get; set; }
        public Nullable<double> CodePaymentAmount { get; set; }
        public Nullable<double> MobilePaymentAmount { get; set; }
        public Nullable<double> CardPayMoney { get; set; }
        public decimal Borrowing { get; set; }
        public decimal Repayment { get; set; }
        public decimal BentoCollection { get; set; }
        public decimal BentoArrearage { get; set; }
        public decimal WatchAmount { get; set; }
        public decimal MobilePhonePayAmount { get; set; }
    }
}
