//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UsId { get; set; }
        public Nullable<int> MerId { get; set; }
        public string Number { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<byte> Sex { get; set; }
        public Nullable<byte> Department { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<byte> IsDisabled { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string IdCard { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public int IsDel { get; set; }
        public System.Guid Gid { get; set; }
        public decimal BorrowAmount { get; set; }
        public decimal RepaymentAmount { get; set; }
        public decimal OweCashAmount { get; set; }
    }
}
